### ISSUE TITLE
Отправка сообщения о успешной покупки

### ISSUE THREAD

**Issue by amnesiaof** [interlumpen/Telegram-shop#1]
Отправка сообщения о успешной покупки в группу админов, вроде id указал, бота в группу добавил, админ права выдал и ничего не пресылает, функционал не дописан?

`if value_data:
            current_time = datetime.datetime.now()
            formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
            buy_item(value_data['id'], value_data['is_infinity'])
            add_bought_item(value_data['item_name'], value_data['value'], item_price, user_id, formatted_time)
            new_balance = buy_item_for_balance(user_id, item_price)
            await bot.edit_message_text(chat_id=call.message.chat.id,
                                        message_id=msg,
                                        text=f'✅ Товар куплен. '
                                             f'<b>Баланс</b>: <i>{new_balance}</i>₽\n\n{value_data["value"]}',
                                        parse_mode='HTML',
                                        reply_markup=back(f'item_{item_name}'))
            user_info = await bot.get_chat(user_id)
            logger.info(f"Пользователь {user_id} ({user_info.first_name})"
                        f" купил 1 товар позиции {value_data['item_name']} за {item_price}р")
###здесь же дописать функционал?
            return`

Так же когда указал канал, то бот при start в консоль прикидывает ошибки а у пользователя и админа ничего не происходит, старт не пропадает меню не появляется

**Comment by interlumpen** [comment]
Привет, на счет первого пункта - это не было предусмотрено, но если вам это нужно, то после последней приведенной вами строки напишите:
`group_id = 'ID of your group'
await bot.send_message(chat_id=group_id,
                                   text=f"<b>Пользователь</b> <code>{user_id}</code> (<i>{user_info.first_name}</i>)\n"
                                        f" <b>купил 1 товар позиции</b> <code>{value_data['item_name']}</code>"
                                        f" за <code>{item_price}</code>р",
                                   parse_mode='HTML')`
если нужно увидеть полученный пользователем товар, добавьте в text также строку `f"<b>товар</b>: <code>{value_data['value']}</code>"`
На счет второго пункта - самостоятельно убедился, что все работает - проверьте, правильно ли вы указали канал, формат ввода должен быть без https://t.me/
также убедитесь, что вы добавили бота в канал и назначили его администратором канала. Если это не помогло, то предоставьте ошибку из консоли.
